name: Automatic testing for continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Display disk space
      run: df -h /

    - name: Maximize build disk space
      # Remove software and language runtimes we're not using
      run: sudo rm -rf \
          "$AGENT_TOOLSDIRECTORY" \
          /opt/google/chrome \
          /opt/microsoft/msedge \
          /opt/microsoft/powershell \
          /opt/pipx \
          /usr/lib/mono \
          /usr/local/julia* \
          /usr/local/lib/android \
          /usr/local/lib/node_modules \
          /usr/local/share/chromium \
          /usr/local/share/powershell \
          /usr/share/dotnet \
          /usr/share/swift

    - name: Display disk space
      run: df -h /

    - name: Set up Python 3.9.16
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.16"

    - name: Install the repository in editable mode
      run: pip install -e ".[dev]"

    - name: Set up jupyter kernel
      run: python -m ipykernel install --name "python3" --user

    - name: Clean up pip cache
      run: pip cache purge

    - name: Test regular tests with pytest
      continue-on-error: true
      run: pytest -m "not require_large_download and not require_download"

    - name: Download data for test
      continue-on-error: true
      run: python scripts/download_pretrained_models.py --skip_large_files

    - name: Test download tests with pytest
      continue-on-error: true
      run: pytest -m "require_download"

    - name: Delete downloaded data
      run: rm -rf data/results
